# /qompassai/yaml/github/workflows/ci.yml
# ------------------------------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved

name: Diver CI

on: [push, pull_request]

jobs:
  test:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - uses: actions/checkout@v4

      - name: Check formatting
        run: stylua .

      - name: Validate LSP config
        run: lua-language-server --check lua

      - name: Launch Neovim in headless mode
        run: nvim --headless +"checkhealth" +qall
