name: Build and test

on: [push, pull_request, workflow_dispatch]

jobs:
  build-test:
    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        go-version: ['stable', 'oldstable']
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: 'touch */*.ts'

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - run: make build

      - run: 'mkdir -p tmp && TMPDIR=$PWD/tmp make test'

      - uses: actions/upload-artifact@v3
        with:
          path: cover.html

      - run: 'make fmt'

      - run: git diff --exit-code
