name: Lint

on:
  pull_request:
  push:
jobs:
  lint:
    name: Lint

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Install current Bash on macOS
        if: runner.os == 'macOS'
        run: |
          command -v brew && brew install bash || true

      - uses: DeterminateSystems/nix-installer-action@v15
        continue-on-error: true

      - name: Install Bunker
        run: |
          if ! command -v bunker &> /dev/null; then
            ./.github/install-bunker-ci.sh
          fi

      - name: Configure Bunker
        run: |
          : "${BUNKER_SERVER:=https://staging.bunker.rs/}"
          : "${BUNKER_CACHE:=bunker-ci}"
          echo BUNKER_CACHE=$BUNKER_CACHE >>$GITHUB_ENV
          export PATH=$HOME/.nix-profile/bin:$PATH # FIXME
          bunker login --set-default ci "$BUNKER_SERVER" "$BUNKER_TOKEN"
          bunker use "$BUNKER_CACHE"
        env:
          BUNKER_SERVER: ${{ secrets.BUNKER_SERVER }}
          BUNKER_CACHE: ${{ secrets.BUNKER_CACHE }}
          BUNKER_TOKEN: ${{ secrets.BUNKER_TOKEN }}

      - name: Cache dev shell
        run: |
          .ci/cache-shell.sh
          system=$(nix-instantiate --eval -E 'builtins.currentSystem')
          echo system=$system >>$GITHUB_ENV

      - name: Check rustfmt
        run: .ci/run just ci-rustfmt
