# ~/.GH/Qompass/Zig/.github/workflows/flakehub-publish-rolling.yaml
# -----------------------------------------------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved

name: Publish every Git push to main to FlakeHub
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  flakehub-publish:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-push@main
        with:
          name: DeterminateSystems/flakehub-push
          rolling: true
          visibility: public
